# .github/workflows/terraform.yml
# Terraform Blue-Green CI/CD  (staging → blue, main → flip prod)

name: Terraform Blue-Green Deploy

on:
  pull_request:
  push:
    branches: [staging, main]

jobs:
  terraform:
    runs-on: ubuntu-latest

    # Global env: no colour output, region for all AWS calls
    env:
      TF_CLI_ARGS: "-no-color"
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    defaults:
      run:
        shell: bash
        working-directory: infra/gateway   # all TF commands run here

    steps:
      # ────────────────────────────────────
      - name: Check out repo
        uses: actions/checkout@v3

      # ────────────────────────────────────
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      # ────────────────────────────────────
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      # ────────────────────────────────────
      - name: Cache Terraform providers
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      # ────────────────────────────────────
      - name: Init & select workspace
        id: ws
        run: |
          terraform init -reconfigure
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            WS=production
          else
            WS=staging
          fi
          terraform workspace list | grep -q "$WS" || terraform workspace new "$WS"
          terraform workspace select "$WS"
          echo "ws=$WS" >> "$GITHUB_OUTPUT"

      # ────────────────────────────────────
      - name: Decide next colour (blue / green)
        id: colour
        run: |
          if [[ "${{ steps.ws.outputs.ws }}" == "production" ]]; then
            if terraform state list | grep -q 'aws_apigatewayv2_stage.bg_stage'; then
              CURRENT=$(terraform state show aws_apigatewayv2_stage.bg_stage | awk '/name/ {print $3}')
              [[ "$CURRENT" == "blue" ]] && NEXT=green || NEXT=blue
            else
              NEXT=blue   # first prod deploy
            fi
          else
            NEXT=blue     # staging always blue
          fi
          echo "Deploying colour: $NEXT"
          echo "next=$NEXT" >> "$GITHUB_OUTPUT"

      # ────────────────────────────────────
      - name: Terraform plan (PR only)
        if: github.event_name == 'pull_request'
        run: |
          terraform plan \
            -var="environment=${{ steps.ws.outputs.ws }}" \
            -var="deployment_color=${{ steps.colour.outputs.next }}"

      # ────────────────────────────────────
      - name: Terraform apply (push to staging/main)
        if: github.event_name == 'push'
        run: |
          terraform apply -auto-approve \
            -var="environment=${{ steps.ws.outputs.ws }}" \
            -var="deployment_color=${{ steps.colour.outputs.next }}"
