name: Terraform Blue-Green Deploy

on:
  pull_request:
  push:
    branches: [staging, main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_CLI_ARGS: "-no-color"

    defaults:
      run:
        shell: bash
        working-directory: infra/gateway

    steps:
      # 1. Check out code
      - uses: actions/checkout@v3

      # 2. Install Terraform CLI
      - uses: hashicorp/setup-terraform@v2

      # 3. Configure AWS credentials from repo secrets
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 4. Cache downloaded providers to speed up builds
      - name: Cache Terraform providers
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      # 5. Select or create the correct workspace
      - name: Select workspace (staging or production)
        id: ws
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            WS=production
          else
            WS=staging
          fi
          terraform workspace list | grep -q "$WS" || terraform workspace new "$WS"
          terraform workspace select "$WS"
          echo "ws=$WS" >> "$GITHUB_OUTPUT"

      # 6. Init Terraform
      - name: Terraform init
        run: terraform init -reconfigure

      # 7. Decide which colour to deploy
      - name: Decide next colour
        id: colour
        run: |
          if [[ "${{ steps.ws.outputs.ws }}" == "production" ]]; then
            CURRENT=$(terraform state list | grep aws_apigatewayv2_stage.bg_stage || true)
            if [[ "$CURRENT" == *"blue"* ]]; then NEXT=green; else NEXT=blue; fi
          else
            NEXT=blue
          fi
          echo "Deploying colour: $NEXT"
          echo "next=$NEXT" >> "$GITHUB_OUTPUT"

      # 8. Plan on pull-request events
      - name: Terraform plan
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          terraform plan \
            -var="environment=${{ steps.ws.outputs.ws }}" \
            -var="deployment_color=${{ steps.colour.outputs.next }}"

      # 9. Apply on pushes to staging / main
      - name: Terraform apply
        if: ${{ github.event_name == 'push' }}
        run: |
          terraform apply -auto-approve \
            -var="environment=${{ steps.ws.outputs.ws }}" \
            -var="deployment_color=${{ steps.colour.outputs.next }}"
